### ISSUE TITLE
Resolution problem on mac Retina

### ISSUE THREAD

**Issue by MangelMaxime** [Calinou/gdscript-online#1]
I think the application is not handling correctly high-resolution screen like Retina.

<img width="1918" alt="Capture d’écran 2019-06-26 à 22 56 09" src="https://user-images.githubusercontent.com/4760796/60214430-c1ad7500-9865-11e9-9b24-a6ae8bbbaddf.png">

**Comment by Calinou** [comment]
I noticed this during testing too. I know how to handle hiDPI support in general, but I'm not sure how to detect whether the display is hiDPI from WebAssembly.

**Comment by jay-jlm** [comment]
@Calinou , why not just have a dropdown or even a simple toggle switch and let users switch between 
 predefined font sizes?

**Comment by Calinou** [comment]
@jay-jlm This isn't actually needed once some kind of scaling support is added. Moreover, scaling just the font size without scaling other 2D elements will look bad.

I have a fix ongoing, I just need to commit and deploy it.

**Comment by jay-jlm** [comment]
Well, looks are nice, but I believe most ppl would be quite happy just to be able to use it, right now it is unreadable in a 13 inch macbook screen.
It's great you have a proper fix, though! Let me know when it has been deployed so I can test it. 
Thank you!

**Comment by Calinou** [comment]
The font size is already fairly large compared to many text editors out there (it's the same as the Godot editor). Making it any larger would hamper usability on lower resolution displays.

[The fix is already deployed](https://gdscript-online.github.io/). Make sure to clear your cache before loading the page.
