### ISSUE TITLE
No virtual Keyboard on Firefox for Android

### ISSUE THREAD

**Issue by winston-yallow** [Calinou/gdscript-online#2]
On Firefox for Android no virtual keyboard appears when tapping in the editor. The execution of GDScript works fine, it is only the virtual keyboard that is not triggered. 
I am not sure if this is very important thought, as mobile probably is not a focus of this project.

Firefox for Android:  
**v67.0.3** 

Tested Android Versions:  
**v7.1.1**  (on Wiko U Feel)  
**v9.0**  (in an emulator. Hardware keyboard is working very good, virtual software keyboard is not triggered even with "do not use hardware keyboard" settings)

**Comment by Calinou** [comment]
This is a bug in Godot's HTML5 export; it's not specific to this project.

**Comment by ShalokShalom** [comment]
Is this already fixed? (In the export)

**Comment by Calinou** [comment]
@ShalokShalom Not yet, as the [virtual keyboard PR](https://github.com/godotengine/godot/pull/41097) hasn't been merged yet.
