### ISSUE TITLE
Flashing black on Firefox

### ISSUE THREAD

**Issue by nathanfranke** [Calinou/gdscript-online#3]
Could be a GLES2 issue, not sure.

https://i.imgur.com/0Vt9UEa.mp4

**Comment by Calinou** [comment]
I can reproduce this on Firefox 75. This appears to be a browser-specific issue which I can also reproduce in applications that make use of hardware acceleration such as <https://keithclark.co.uk/labs/css-fps/>. (Can you reproduce it there as well?)

The only way to fix this so far is to disable low-processor usage mode, which I'd really not prefer to do.

See also https://github.com/godotengine/godot/issues/38623.

PS: Which graphics card model do you have?

**Comment by nathanfranke** [comment]
Oops, forgot to include more information.

OS: Linux Mint 19.3
GPU: Nvidia GTX 960, Driver version 435.21-0ubuntu0.18.04.2
Firefox 76

**Comment by eon-s** [comment]
Got the same effect on FF 77, Ubuntu 20.04 on a R5 (Carrizo, amdgpu).

**Comment by Calinou** [comment]
This might be fixed by https://github.com/godotengine/godot/pull/39604 once it's merged.

**Comment by Calinou** [comment]
This appears to have been fixed in recent Firefox versions (tested on Firefox 83 on Fedora 33), closing.
