### ISSUE TITLE
Wrong pixel ratio on retina screen

### ISSUE THREAD

**Issue by setanarut** [Calinou/gdscript-online#4]
Display is too small
<img width="561" alt="cap 1" src="https://user-images.githubusercontent.com/36481442/92986113-241d8000-f4c1-11ea-9994-afd1fc5d7bb6.png">

**Comment by Calinou** [comment]
[This should no longer occur](https://github.com/Calinou/gdscript-online/issues/1), but I guess getting the screen DPI doesn't work correctly in HTML5…

I could switch the project to use the `2d` stretch mode, but this means you won't be able to gain any screen real estate past the design window size (which would be something like 1366×768 to support all displays).

**Comment by setanarut** [comment]
I'm not familiar with the subject but [gd.tumeo.space](https://gd.tumeo.space) looks normal. maybe gives an idea.

**Comment by Calinou** [comment]
@hazarek gd.tumeo.space isn't a Godot project exported to HTML5, it's a standard web page.

**Comment by setanarut** [comment]
@Calinou I found the workaround
right click Chrome/Firefox/Safari.app  > Get info > Open in low resolution
