### ISSUE TITLE
possible Code stepping functionality to imitate yield / deferred code

### ISSUE THREAD

**Issue by Haledire** [Calinou/gdscript-online#6]
Right now the output window doesn't support code that will do any sort of deferring.  Is it feasible to add a button to step through code that holds a yield?

IE:  If I try to give someone an example of what a variable holding a node has after queue_free():
```gdscript
func _ready():
   var node = Node.new()
   add_child(node)
   node.queue_free()
   yield(get_tree(), "idle_frame")
   print(node)
```
this actually prints the node, which it shouldn't as the yield should be after the node has left meaning it should print
[Deleted Node]

There are other situations where code after yields are just never run obviously because you can't return from a yield ie: `yield(get_tree().create_timer(1), "timeout")` because there's nothing actively running the code to reach that point, but it would be nice to be able to step over the code as if you were resuming from the yield to see "more accurate" simulated results.

If it's out of scope of the project that's fine.  I was just curious.

**Comment by Calinou** [comment]
> Right now the output window doesn't support code that will do any sort of deferring. Is it feasible to add a button to step through code that holds a yield?

GDScript Online is exported in release mode and does not include editor functionality. Therefore, it does not have access to debugger functionality, as this is only available in the editor (and debug builds in general). This is also why `get_stack()` can't be used to display error messages, for instance.

Closing, as this is not technically feasible to implement. I suppose I could add a check that warns the user if `yield(` is found anywhere in the source code to make it clear that this use case isn't supported.
